#index:
#    path: /
#    controller: App\Controller\DefaultController::index

blog_list:
  path: /blog/list/{page}
  defaults:
      _controller: App\Controller\BlogController::list
      format: json
      page: 1
  requirements:
      page: '^[0-9]+$'
blog_by_id:
  path: /blog/id/{id}
#  methods: GET
  defaults:
      _controller: App\Controller\BlogController::post
      format: json
      id: 1
  requirements:
    id: '\d+'
blog_by_slug:
  path: /blog/slug/{slug}
#  methods: GET
  defaults:
      _controller: App\Controller\BlogController::postBySlug
      format: json
blog_add:
  path: /blog/add
  methods: POST
  defaults:
    _controller: App\Controller\BlogController::add
blog_add_test:
  path: /blog/addTest
  defaults:
    _controller: App\Controller\BlogController::addTest
blog_delete:
  path: /blog/delete/{id}
#  methods: DELETE
  defaults:
    _controller: App\Controller\BlogController::delete
  requirements:
    id: '^[0-9]+$'


